services:
  # Python Application Service
  tg_bot:
    build: .
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: 123456
      DB_NAME: LotteryBotDB
    depends_on:
      - db
    networks:
      - app-network

  # PostgreSQL Database Service
  db:
    image: postgres:13  # Use the official PostgreSQL image
    ports:
      - "7654:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: LotteryBotDB
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persist database data
    networks:
      - app-network
      
networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: