"""Add winner to lottery

Revision ID: 365833434c27
Revises: d47d7d8a3101
Create Date: 2025-03-05 12:57:11.721022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '365833434c27'
down_revision: Union[str, None] = 'd47d7d8a3101'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Lotteries', sa.Column('winnerId', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'Lotteries', 'Users', ['winnerId'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Lotteries', type_='foreignkey')
    op.drop_column('Lotteries', 'winnerId')
    # ### end Alembic commands ###
