"""Add date to ticket

Revision ID: d47d7d8a3101
Revises: 4f060b3c4f32
Create Date: 2025-03-05 12:29:21.630013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd47d7d8a3101'
down_revision: Union[str, None] = '4f060b3c4f32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('LotteryUsers', sa.Column('buyDate', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('LotteryUsers', 'buyDate')
    # ### end Alembic commands ###
