"""username

Revision ID: d556655e691e
Revises: 365833434c27
Create Date: 2025-03-14 19:54:28.238280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd556655e691e'
down_revision: Union[str, None] = '365833434c27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('Lotteries_winnerId_fkey', 'Lotteries', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('Lotteries_winnerId_fkey', 'Lotteries', 'Users', ['winnerId'], ['id'])
    # ### end Alembic commands ###
